name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'vtai-todo-app@todo-backend-376718.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'

      # Example of using the output
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
